joy_node:
  ros_parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0
    dev : '/dev/input/js0'

teleop_twist_node:
  ros_parameters:
    axis linear:
      x: 0
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis angular:
      yaw: 1
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    # enable_button: false
    # enable_turbo_button: 3

    # require_enable_button: true