version: "3.9"
services:
  base:
    image: group4-mob-rob:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=host.docker.internal:0.0
      - QT_X11_NO_MTTSHM=1
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: /dev
        target: /dev
    device_cgroup_rules:
      - 'c *:* mrw'



